
disabled_rules: # rule identifiers to exclude from running
# warning
# - nesting
# - identifier_name
# error
 - line_length
# - file_length
#opt_in_rules: # some rules are only opt-in
#  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included:
  - ../HPLiveKit
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

reporter: "xcode"
