use_frameworks!

platform :ios, '11.0'

inhibit_all_warnings!
target 'HPLiveKit_Example' do
  pod 'HPLiveKit', :path => '../'

  target 'HPLiveKit_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
    pod 'SwiftLint'
  end
end
