source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '14.0'

inhibit_all_warnings!
target 'HPLiveKit_Example' do

  target 'HPLiveKit_Tests' do
    inherit! :search_paths
    pod 'SwiftLint'
  end
end
