name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1 
    - name: Select Xcode version 
      run: sudo xcode-select -s '/Applications/Xcode_11.3.1.app/Contents/Developer'
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Install cocoapods
      run: cd Example;pod install
    - name: Build 
      run: cd Example;xcodebuild  -workspace HPLiveKit.xcworkspace -scheme HPLiveKit-Example -sdk iphonesimulator -configuration Debug build
